# Loss Functions

In [1]:
import torch
import torch.nn as nn

In [2]:
input = torch.randn(3, 5, requires_grad=True)
input

tensor([[-1.0273, -0.1234,  0.6868,  1.1147, -1.0249],
        [-0.7682, -0.3694,  0.7461, -0.8654, -0.9053],
        [ 0.5690, -0.5255, -1.6316,  0.4982, -0.1921]], requires_grad=True)

In [3]:
# each element in target has to have 0 <= value < C
target = torch.tensor([1, 0, 4])
target

tensor([1, 0, 4])

### `nn.Softmax` ([docs](https://pytorch.org/docs/stable/nn.html#softmax))

In [4]:
m = nn.Softmax(dim=1)
m(input)

tensor([[0.0539, 0.1332, 0.2994, 0.4594, 0.0541],
        [0.1134, 0.1690, 0.5157, 0.1029, 0.0989],
        [0.3516, 0.1177, 0.0389, 0.3276, 0.1642]], grad_fn=<SoftmaxBackward>)

In [5]:
m(input).sum(axis=1)

tensor([1.0000, 1.0000, 1.0000], grad_fn=<SumBackward1>)

### `nn.LogSoftmax` ([docs](https://pytorch.org/docs/stable/nn.html#torch.nn.LogSoftmax))

Applies the log(Softmax(x)) function to an n-dimensional input Tensor.

In [6]:
m1 = nn.LogSoftmax(dim=1)
m2 = nn.Softmax(dim=1)

In [7]:
m1(input)

tensor([[-2.9199, -2.0160, -1.2058, -0.7779, -2.9175],
        [-2.1765, -1.7777, -0.6622, -2.2738, -2.3136],
        [-1.0453, -2.1398, -3.2459, -1.1161, -1.8064]],
       grad_fn=<LogSoftmaxBackward>)

In [8]:
torch.log(m2(input))

tensor([[-2.9199, -2.0160, -1.2058, -0.7779, -2.9175],
        [-2.1765, -1.7777, -0.6622, -2.2738, -2.3136],
        [-1.0453, -2.1398, -3.2459, -1.1161, -1.8064]], grad_fn=<LogBackward>)

Note, you should not do this IRL due to poor numerical properties.

### `nn.NLLLoss` ([docs]())

The negative log likelihood loss. It is useful to train a classification problem with C classes.

In [9]:
m = nn.LogSoftmax(dim=1)
loss = nn.NLLLoss()
output = loss(m(input), target)
output.backward()

In [10]:
m(input)

tensor([[-2.9199, -2.0160, -1.2058, -0.7779, -2.9175],
        [-2.1765, -1.7777, -0.6622, -2.2738, -2.3136],
        [-1.0453, -2.1398, -3.2459, -1.1161, -1.8064]],
       grad_fn=<LogSoftmaxBackward>)

In [11]:
output

tensor(1.9996, grad_fn=<NllLossBackward>)

### `nn.CrossEntropyLoss` ([docs](https://pytorch.org/docs/stable/nn.html#crossentropyloss))

This criterion combines `nn.LogSoftmax()` and `nn.NLLLoss()` in one single class.

In [12]:
loss = nn.CrossEntropyLoss()
output = loss(input, target)
output.backward()

In [13]:
output

tensor(1.9996, grad_fn=<NllLossBackward>)