# Object Oriented Programming

A quick reference about OOO in Python. Not specific to PyTorch. Covers some not-so-well-known/used aspects of OOP for Data Scientists. 

Currently, it covers:

- Special methods (e.g., `__len__`, `__repr__`)
- Inheritance
- staticmethod and classmethod

Todo:
- Properties


In [1]:
import platform; print("Platform", platform.platform())
import sys; print("Python", sys.version)

Platform Linux-4.15.0-1060-aws-x86_64-with-debian-buster-sid
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0]


In [2]:
import numpy as np
x = np.random.rand(4, 8)
y = np.random.randint(0, 2, size=(4, 3))

## Special Methods

### `__repr__` or `__str__` are what happens when you print an object. 

Some advice I've found ([here](https://stackoverflow.com/questions/1436703/difference-between-str-and-repr) and [here](https://stackoverflow.com/questions/1436703/difference-between-str-and-repr/1436756#1436756)) is to make `__str__` more readable version `__repr__` if necessary and that every class should have a `__repr__`.

In [3]:
class Data:
    
    def __init__(self, x, y):
        self.x = x
        self.y = y
    
    def __repr__(self):
        return f"Data(X={[x.shape[0],x.shape[1]]}, Y={[y.shape[0],y.shape[1]]})"
    
    def __str__(self):
        return f"Data has {x.shape[0]} rows, " + \
        f"{x.shape[1]} columns, and {y.shape[1]} classes"

In [4]:
data = Data(x, y)

In [5]:
print(str(data))

Data has 4 rows, 8 columns, and 3 classes


In [6]:
print(repr(data))

Data(X=[4, 8], Y=[4, 3])


In [7]:
data # Looks like Jupyter uses repr by default

Data(X=[4, 8], Y=[4, 3])

In [8]:
print(data) # Looks like python uses print(str) by default

Data has 4 rows, 8 columns, and 3 classes


### `__len__` is what happens when you call `len(obj`.

In [9]:
class Data:
    
    def __init__(self, x, y):
        self.x = x
        self.y = y
    
    def __repr__(self):
        return f"Data(X={[x.shape[0],x.shape[1]]}, Y={[y.shape[0],y.shape[1]]})"
    
    def __str__(self):
        return f"Data has {x.shape[0]} rows, " + \
        f"{x.shape[1]} columns, and {y.shape[1]} classes"
    
    def __len__(self):
        return x.shape[0]

In [10]:
data = Data(x, y)
len(data)

4

### `__iter__` is what happens when you try to iterate through a for loop.

In [11]:
class Data:
    
    def __init__(self, x, y):
        self.x = x
        self.y = y
    
    def __repr__(self):
        return f"Data(X={[x.shape[0],x.shape[1]]}, Y={[y.shape[0],y.shape[1]]})"
    
    def __str__(self):
        return f"Data has {x.shape[0]} rows, " + \
        f"{x.shape[1]} columns, and {y.shape[1]} classes"
    
    def __len__(self):
        return x.shape[0]
    
    def __iter__(self):
        for i in range(len(self)):
            yield x[i,:], y[i,:]

In [12]:
data = Data(x, y)
for d in data:
    print(d)

(array([0.41794565, 0.16896076, 0.34962879, 0.18401298, 0.59416806,
       0.25896057, 0.40572897, 0.554468  ]), array([0, 0, 1]))
(array([0.76751111, 0.47275089, 0.12654282, 0.87752298, 0.62757249,
       0.07713261, 0.3371223 , 0.46789909]), array([1, 0, 1]))
(array([0.37341372, 0.01939083, 0.41243808, 0.95163653, 0.12225101,
       0.86191834, 0.03563386, 0.87389153]), array([0, 0, 1]))
(array([0.31591386, 0.21205521, 0.5229539 , 0.88034027, 0.71658461,
       0.84195059, 0.640154  , 0.59905214]), array([1, 1, 0]))


### `__getitem__(self, i)` is what happens when you slice a dataset.

In [13]:
class Data:
    
    def __init__(self, x, y):
        self.x = x
        self.y = y
    
    def __repr__(self):
        return f"Data(X={[x.shape[0],x.shape[1]]}, Y={[y.shape[0],y.shape[1]]})"
    
    def __str__(self):
        return f"Data has {x.shape[0]} rows, " + \
        f"{x.shape[1]} columns, and {y.shape[1]} classes"
    
    def __len__(self):
        return x.shape[0]
    
    def __iter__(self):
        for i in range(len(self)):
            yield x[i,:], y[i,:]
            
    def __getitem__(self, i):
        return self.x[i, :], self.y[i, :]

In [14]:
data = Data(x, y)
data[2]

(array([0.37341372, 0.01939083, 0.41243808, 0.95163653, 0.12225101,
        0.86191834, 0.03563386, 0.87389153]), array([0, 0, 1]))

In [15]:
data[2:4]

(array([[0.37341372, 0.01939083, 0.41243808, 0.95163653, 0.12225101,
         0.86191834, 0.03563386, 0.87389153],
        [0.31591386, 0.21205521, 0.5229539 , 0.88034027, 0.71658461,
         0.84195059, 0.640154  , 0.59905214]]), array([[0, 0, 1],
        [1, 1, 0]]))

### `__call__(self, args)` is what happens when you call the object

In [16]:
class Data:
    
    def __init__(self, x, y):
        self.x = x
        self.y = y
    
    def __repr__(self):
        return f"Data(X={[x.shape[0],x.shape[1]]}, Y={[y.shape[0],y.shape[1]]})"
    
    def __str__(self):
        return f"Data has {x.shape[0]} rows, " + \
        f"{x.shape[1]} columns, and {y.shape[1]} classes"
    
    def __len__(self):
        return x.shape[0]
    
    def __iter__(self):
        "Note the usage of __len__"
        for i in range(len(self)):
            yield x[i,:], y[i,:]
            
    def __getitem__(self, i):
        return self.x[i, :], self.y[i, :]
    
    def __call__(self):
        """Get a random sample of x.
        Note the usage of __len__ and __getitem__"""
        return self[np.random.randint(0, len(self))]

In [17]:
data = Data(x, y)

In [18]:
data()

(array([0.76751111, 0.47275089, 0.12654282, 0.87752298, 0.62757249,
        0.07713261, 0.3371223 , 0.46789909]), array([1, 0, 1]))

In [19]:
data()

(array([0.41794565, 0.16896076, 0.34962879, 0.18401298, 0.59416806,
        0.25896057, 0.40572897, 0.554468  ]), array([0, 0, 1]))

## Inheritance

In [20]:
class Trainer:
    
    def __init__(self, n_iter):
        self.n_iter = n_iter
    
    def run_training(self):
        for i in range(self.n_iter):
            print(f"{i+1}/{self.n_iter} epochs complete")

Next, we create a more specific (aka child) class which will inherit the methods from the more abstract class (aka parent). Additionally, you can use the more specific class to specify attributes in the original class.

In [21]:
class ImageTrainer(Trainer):
    
    def load_image_data(self):
        print(f"Loaded data")

In [22]:
it = ImageTrainer(n_iter=5)
it.load_image_data()

Loaded data


In [23]:
it.run_training()

1/5 epochs complete
2/5 epochs complete
3/5 epochs complete
4/5 epochs complete
5/5 epochs complete


## Decorators

### `@staticmethod` does not have access to the state of the object and is used as an utility function.

In [24]:
class Predictor:
    
    @staticmethod
    def predict(x, thresh):
        return (x > thresh).astype(int)

In [25]:
pred = Predictor()
pred.predict(np.random.rand(10), 0.50)

array([1, 0, 1, 1, 1, 0, 0, 1, 0, 0])

### `@classmethod`

In [26]:
class Predictor:
    
    def __init__(self, thresh=0.25):
        self.thresh = thresh
    
    @classmethod
    def get_predictor(cls, thresh):
        return cls(thresh)
    
    def predict(self, x):
        return (x > self.thresh).astype(int)

In [27]:
pred = Predictor().get_predictor(0.5)

In [28]:
x = np.random.rand(8); print(x)
pred.predict(x)

[0.46368406 0.20669878 0.69799196 0.96250332 0.93071782 0.16336832
 0.71885213 0.78401567]


array([0, 0, 1, 1, 1, 0, 1, 1])